version: '3.4'
services:

    for_mysql:
      expose:
        - "3306"
      image: mysql:5.7.25
      environment:
        - MYSQL_ROOT_PASSWORD=pass1234
      volumes:
        - ./mysqldata:/var/lib/mysql
    nginx:
      restart: always
      image: nginx:1.15.9
      volumes:
        - ./demo/static:/docker_api/demo/static
        - ./demo/upload:/docker_api/demo/upload
        - ./nginx/conf.d:/etc/nginx/conf.d
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      env_file:
        - ./env/.env
      ports:
        - target: "8000"
          published: "8000"
          mode: host
        - target: "80"
          published: "80"
          mode: host
    demo:
      build: ./demo
      restart: always
      volumes:
        - ./demo:/docker_api
      depends_on:
        - for_mysql

volumes:
    mysqldata:
